const customerList = [
  {
    id: 1,
    name: "ratheesh",
    emailId: "ratheesh@gmail.com",
    countryCode: "91",
    mobileNo: "95554357812",
    gender: "male",
  },
  {
    id: 2,
    name: "rafe",
    emailId: "rafe@gmail.com",
    countryCode: "91",
    mobileNo: "815151121515",
    gender: "male",
  },
  {
    id: 3,
    name: "sai madhu nandhini",
    emailId: "nandhini@gmail.com",
    countryCode: "91",
    mobileNo: "805248055512",
    gender: "female",
  },
  {
    id: 4,
    name: "xavier raj",
    emailId: "xavier@gmail.com",
    countryCode: "91",
    mobileNo: "854545545485",
    gender: "male",
  },
  {
    id: 5,
    name: "suresh",
    emailId: "suresh@live.com",
    countryCode: "91",
    mobileNo: "5468485315",
    gender: "male",
  },
  {
    id: 6,
    name: "tamil selvan",
    emailId: "tamilselvan@windowslive.com",
    countryCode: "91",
    mobileNo: "135151353135135",
    gender: "male",
  },
  {
    id: 7,
    name: "sathya",
    emailId: "sathya@adithyagroup.com",
    countryCode: "91",
    mobileNo: "44645878745646",
    gender: "female",
  },
  {
    id: 8,
    name: "ashwini",
    emailId: "ashwini@sutehrlandglobal.com",
    countryCode: "95",
    mobileNo: "95554357888",
    gender: "female",
  },
  {
    id: 9,
    name: "bill gates",
    emailId: "billgates@windows.com",
    contryCode: "1",
    mobileNo: "951561546462",
    gender: "male",
  },
  {
    id: 10,
    name: "ruppa",
    emailId: "ruppa@gmail.com",
    countryCode: "91",
    mobileNo: "9555454846546",
    gender: "female",
  },
];
export default customerList;
